blank_issues_enabled: true
contact_links:
  - name: General scientific question
    url: https://github.com/MrL0utre/circuitpartitioning/discussions
    about: Use discussions for a question that is not yet a well-defined task.
