blank_issues_enabled: true
contact_links:
  - name: Question scientifique générale
    url: https://github.com/MrL0utre/circuitpartitioning/discussions
    about: Utiliser les discussions pour une question qui n'est pas encore une tâche définie.

